### ISSUE TITLE
Question: How to update a private repo with a release asset?

### ISSUE THREAD

**Issue by claytoncollie** [YahnisElsts/plugin-update-checker#403]
I am looking through all of the issues to find a solution and can't figure this out. Somewhat related to your work done on #93

I have a private repo that when I release a new version, the plugin is built (`composer install`) and then an archive is made and finally attached to the release as `<repo-slug>.zip`.

I am following your readme to authenticate my request and then to enable release assets and finally I add a parameter to the enable release assets method to look for the archive with the name `<repo-slug>.zip` like I mentioned above after reading this issue #370 and  #230 

WordPress throws an error on updating the plugin.

```Update failed: The directory structure of the update is incorrect. All files should be inside a directory named content-pilot-developer, not at the root of the ZIP archive.```

Am I doing something incorrectly? I understand the archive contents are at the root but I don't want to nest my contents inside another directory inside my plugin. Is that even a solution?

Here is my code

```
$this->slug = 'content-pilot-developer';
```

```
$update_checker = \Puc_v4_Factory::buildUpdateChecker(
	sprintf(
		'https://github.com/content-pilot/%s',
		esc_attr( $this->slug )
	),
	sprintf(
		'%s/wp-content/plugins/%s/%s.php',
		ABSPATH,
		esc_attr( $this->slug ),
		esc_attr( $this->slug )
	),
	esc_attr( $this->slug )
);

// Authentication from WordPress option.
$global_settings = get_option( 'content_pilot_global_settings' );
if ( ! empty( $global_settings ) ) {
	if ( isset( $global_settings['access_token'] ) ) {
		$update_checker->setAuthentication( $global_settings['access_token'] );
	}
}

// Use release assets to get built version.
$update_checker->getVcsApi()->enableReleaseAssets( '/' . $this->slug . '/' );
```

I made the repo public so that you could see it and so that I could test as public too.

https://github.com/content-pilot/content-pilot-developer/releases/tag/2.3.5

**Comment by YahnisElsts** [comment]
As the error message says, the plugin files should be inside a directory. If you don't want to do that, you'll have to do one of the following:

- Figure out how to make your directory structure work with the WordPress plugin updater. As far as I know, WordPress doesn't support that, but maybe you can find some kind of a workaround.
- Write your own update installer. PUC lets WordPress core do the installation, but you could technically write your own script to download, extract and replace the files yourself. I did something like that 10+ years ago when WordPress didn't support automatic plugin updates. This could be a lot of work.
- Find a different update checker that already includes that feature. While I'm not aware of any projects like that, they could be out there. There definitely are other update checkers, e.g. [GitHub Updater](https://github.com/afragen/github-updater).

**Comment by claytoncollie** [comment]
As a test, I nested my plugin inside itself, inside the archive so the directory structure was content-pilot-developer/content-pilot-developer/** files then used the normal plugin installer and that didn't work. 

Is that what you mean by having the file be inside a directory?

**Comment by YahnisElsts** [comment]
Are you on a Mac by any chance? I've heard that the default ZIP utility on that platform can make it looks like the files in ZIP archive are inside a directory when they're actually not. 

> Is that what you mean by having the files be inside a directory?

I mean that when you open the ZIP archive, the first thing you should see is a directory with the same name as the plugin slug. All of the plugin files (like the main .php file and so on) should be inside that directory. You can look at any plugin ZIP from wordpress.org to see what that looks like. For example: [the latest Akismet version](https://downloads.wordpress.org/plugin/akismet.4.1.7.zip).

**Comment by claytoncollie** [comment]
When I download Akismet and open it on my mac, I see the exact same structure as my release asset.

**Comment by claytoncollie** [comment]
Lookin at woocommerce, their build process looks very similar and so does their release structure.

https://github.com/woocommerce/woocommerce/releases/tag/4.8.0

**Comment by YahnisElsts** [comment]
Your release is no longer public, but when I looked at it earlier, I saw that the plugin files were at the root of the archive instead of being in a directory. On the other hand, the `woocommerce.zip` file in the release that you linked does have a directory named `woocommerce` inside it, and all of the WooCommerce files are inside that directory. 

It sounds like the OS is the problem in this case. Try using a different ZIP archiver. I'm not sure what's available for macOS. WinZip? iZip?

**Comment by claytoncollie** [comment]
Thanks for clarifying. Once I get my archive sorted out properly, will I still need to fill in the parameter like below?

```
$update_checker->getVcsApi()->enableReleaseAssets( '/' . $this->slug . '/' );
```

**Comment by YahnisElsts** [comment]
If you want to use release assets then you still need to call `enableReleaseAssets()`, but you might be able to leave out the parameter. Without the parameter, the update checker will automatically pick the first available asset. So if each of your releases only has one asset, you don't really need the parameter.

**Comment by claytoncollie** [comment]
I adjusted my archive to have a single directory just like Woocommerce, removed the regex in the `enableReleaseAssets()` parameter and my plugins update perfectly from a GitHub Action.  Thank you for talking me through it. Much appreciated.

Here is my release action in case anybody else wants it.

```
name: Tag, Build, Release
on:
  push: 
    # Run when tag is pushed to repository
    # Pattern matching for semantic version number
    # https://semver.org/#summary
    tags:
    - '*.*.*' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Checkout code
        uses: actions/checkout@v2
      # Create our release with tag as name
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Release for version ${{ github.ref }}
          draft: false
          prerelease: false
      # Run Composer to build dist version
      # Create empty directory to later house our ZIP archive
      - name: Build
        run: |
          composer install --no-dev --optimize-autoloader --ansi --no-progress --no-interaction --prefer-dist
          mkdir ${{ github.event.repository.name}}
          rsync -rv --exclude=${{ github.event.repository.name}} --exclude=.* --exclude=.git --exclude=.github --exclude=.vscode --exclude=node_modules --exclude=tests . ${{ github.event.repository.name}}
      # Create ZIP archive of dist version
      # Located in the /build directory we created earlier
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ${{ github.event.repository.name }}.zip ${{ github.event.repository.name}}
      # Upload our ZIP archive as an asset to the release we created earlier
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
```
