### ISSUE TITLE
Release assets fallback to first/default .zip even if releaseassets regex is applied.

### ISSUE THREAD

**Issue by melcarthus** [YahnisElsts/plugin-update-checker#529]
When using the gitlab-ci.yml file of mine I can succesfully build releases for my wordpress theme.
Each release that I build comes with 5 assets 1 of them being a build package containing no source files (no src/scss/gulp files etc...) that i want to use in the plugin update checker.

I'm calling the enableReleaseAssets and using the name of the zip. But 'landingpages.zip' 
But it falls back to the full release asset.

I read in the documentation about the 3 ways to get an update
-tag
-release
-stablebranche

I want to add tags to my release, but I also want to use the custom release assets.

How am I supposed to setup the update checker so it uses the correct release asset and not just the first one it encounters.

I looks like its not working but maybe because i am using tags in my release the custom release assets are ignored? 

I'm kind of stuck and would like some help on this.

### The asset link I want to use

https://gitlab.com/api/v4/projects/22058473/packages/generic/boikon-landingpages/v4.4.6/landingpages.zip

### Release assets
<img width="319" alt="image" src="https://github.com/YahnisElsts/plugin-update-checker/assets/7837653/6e255b8b-e876-45de-862e-8a3959dad121">

### gitlab-ci.yml
```yml
stages:
  - upload
  - release

# Refer to: https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs/examples/release-assets-as-generic-package/
# PACKAGE_VERSION=$(sed -nE 's/^Version: ([0-9.]+)/\1/p' style.css)
upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  artifacts:
      name: "${CI_PROJECT_NAME}"
      paths:
        - ${CI_PROJECT_NAME}.zip
      expire_in: 1 day
  script:
    - |
      PACKAGE_VERSION="${CI_COMMIT_TAG}"
      PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${PACKAGE_VERSION}"
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file ${CI_PROJECT_NAME}.zip ${PACKAGE_REGISTRY_URL}/${CI_PROJECT_NAME}.zip
      echo 'Package uploaded!'
# Refer to: https://gitlab.com/gitlab-org/release-cli/-/tree/master/docs#using-this-tool-in-gitlab-ci

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      PACKAGE_VERSION="${CI_COMMIT_TAG}"
      PACKAGE_REGISTRY_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${PACKAGE_VERSION}"      
      release-cli create \
        --name "Release $CI_COMMIT_TAG" \
        --description "Release of $CI_COMMIT_TAG from $CI_PROJECT_NAME" \
        --tag-name "$CI_COMMIT_TAG" \
        --assets-link "{\"name\":\"${CI_PROJECT_NAME}.zip\",\"url\":\"${PACKAGE_REGISTRY_URL}/${CI_PROJECT_NAME}.zip\"}"
    - |
      echo "Created release of ${CI_PROJECT_NAME}!"

```
